config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :author, presence: true, length: { minimum: 6, maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show        
    end

    def index
        @articles = Article.all        
    end

    def new        
        @article = Article.new()
    end

    def edit        
    end

    def create
        @article = Article.new(params_require)
        if @article.save
            flash[:notice] = "Article was created successfully."
            #redirect_to article_path(@article) # Also the following shorter version:
            redirect_to @article
        else
            render 'new'
        end
    end

    def update
        if @article.update(params_require)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            render 'edit'
        end        
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private 
    
    def set_article
        @article = Article.find(params[:id])
    end

    def params_require
        params.require(:article).permit(:title, :author, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any?  %>
    <h3>The following errors prevented the article to be saved:</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg|  %>
            <li><%= msg  %></li>            
        <% end  %>    
    </ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>

    <p>
        <%= f.label :title %><br />     
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :author %><br />        
        <%= f.text_field :author %>
    </p>    

    <p>
        <%= f.label :description %><br />       
        <%= f.text_area :description %>
    </p>    

    <p>
        
        <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and Return to Articles List', articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing Page</h1>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Description</th>
            <th>Author</th>
            <th colspan="3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.id %></td>
                <td><%= article.title %></td>
                <td><%= article.description %></td>
                <td><%= article.author %></td>
                <td><%= link_to 'Show', article_path(article.id) %></td>
                <td><%= link_to 'Edit', edit_article_path(article.id) %></td>
                <td><%= link_to 'Delete', article_path(article.id), method: :delete, data: { confirm: "Are you sure?" } %></td>
            </tr>            
        <% end %>        
    </tbody>    
</table>

<p>
    <%= link_to 'Create New Article', new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to Articles List', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>ID: </strong><%= @article.id %></p>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Author: </strong><%= @article.author %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to 'Edit', edit_article_path(@article.id) %> |
<%= link_to 'Delete', article_path(@article.id), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to Articles List', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">ALPHA BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Alpha-Blog</h1>
<p>Alpha blog description</p>

<%= link_to 'Articles List', articles_path %>
<%= link_to 'Homepage', root_path %>

app/views/pages/home.html.erb
<h1>Alpha-Blog Homepage</h1>
<p>This is the best blog in the universe</p>

<%= link_to 'Articles List', articles_path %>
<%= link_to 'About', about_path %>